In [1]:
import pandas as pd

In [10]:
pd.set_option("display.max_columns",200)

In [4]:
df=pd.read_csv("survey_results_public.csv",low_memory=False)

In [5]:
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
ind_df=df[df["Country"]=="India"]

In [11]:
ind_df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",NaN,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,NaN,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,NaN,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,NaN,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once every 2 - 3 months,Less than one year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,NaN,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,NaN,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,NaN,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,NaN,NaN,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,NaN,NaN,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,NaN,NaN,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
46,47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,NaN,NaN,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
90,91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",NaN,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,NaN,NaN,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,NaN,NaN,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,NaN,NaN,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,NaN,NaN,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",Less than half of the time,NaN,Very favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Cybersecurity,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0
133,134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,NaN,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,NaN,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,NaN,NaN,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,NaN,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,NaN,AI agents have improved the quality of my code...,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,AutoGen (Microsoft),NaN,NaN,NaN,ChatGPT;Google Gemini;Microsoft Copilot,NaN,When I have ethical or security concerns about...,Problem solving,20109.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49132,49133,I code primarily as a hobby,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Not employed,NaN,NaN,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Videos (not associated ...,"No, I learned something that was not related t...",NaN,3.0,Student,NaN,NaN,NaN,NaN,Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,NaN,2.0,India,INR Indian rupee,NaN,Yes,HTML/CSS;Java;JavaScript;Python;Rust;TypeScript,Rust;TypeScript,Rust;TypeScript,NaN,NaN,Yes,MySQL;Redis;SQLite,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Ansible;Homebrew;Kub...,Kubernetes;npm,Kubernetes;npm,NaN,NaN,Yes,Node.js;React;Axum,Next.js;React;Axum,React;Axum,NaN,NaN,NaN,Cursor;Visual Studio Code,Cursor,Cursor,NaN,NaN,Tailwind CSS 4,Tailwind CSS 4,Tailwind CSS 4,NaN,NaN,MacOS,MacOS,NaN,NaN,NaN,NaN,NaN,Stack Overflow;YouTube,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Less than one year,Less than once every 2 - 3 months,Chat (people),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not really",NaN,"Yes, I use AI tools daily",Favorable,Somewhat trust,Very well at handling complex tasks,NaN,Project planning;Generating content or synthet...,Learning about a codebase;Writing code;Documen...,Debugging or fixing code;Testing code;Committi...,Search for answers,I’ve become less confident in my own problem-s...,NaN,"No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem,Maths,NaN,NaN
49141,49142,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,1.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,5.0,Data engineer,20 to 99 employees,NaN,In-person,"Yes, I influenced the purchase of a substantia...",Work,4.0,6.0,1.0,3.0,5.0,2.0,8.0,9.0,7.0,10.0,NaN,7.0,6.0,2.0,1.0,8.0,9.0,5.0,3.0,4.0,10.0,NaN,Software Development,13.0,10.0,6.0,1.0,4.0,9.0,5.0,14.0,2.0,12.0,7.0,8.0,3.0,15.0,11.0,NaN,Yes,I have strongly considered changing my career ...,10.0,4.0,India,INR Indian rupee,750000.0,Yes,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Java;JavaScript;Python,Java;JavaScript;Python,PySpark,NaN,Yes,Databricks SQL;Dynamodb;MySQL;Snowflake;Amazon...,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Docker;Kubernetes;Te...,Amazon Web Services (AWS);Docker;Kubernetes;Te...,Amazon Web Services (AWS);Docker;Kubernetes;Te...,NaN,NaN,Yes,Express;Node.js,Express;Node.js;Spring Boot,Express;Node.js,NaN,NaN,Yes,Claude Code;Jupyter Notebook/JupyterLab;Visual...,Claude Code;Jupyter Notebook/JupyterLab;Visual...,Claude Code;Jupyter Notebook/JupyterLab;Visual...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;Ubuntu,Windows;Ubuntu,GitHub;GitLab,GitHub;GitLab,GitHub;GitLab,NaN,NaN,Stack Overflow;YouTube;LinkedIn;Medium,Stack Overflow;YouTube;LinkedIn;Medium,Stack Overflow;YouTube;LinkedIn;Medium,NaN,NaN,Yes,Gemini (Pro Reasoning models);openAI GPT (chat...,Gemini (Pro Reasoning models);openAI GPT (chat...,Gemini (Pro Reasoning models);openAI GPT (chat...,NaN,NaN,Yes,Daily or almost daily,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,Job board,3.0,5.0,9.0,6.0,4.0,7.0,2.0,8.0,1.0,10.0,NaN,"Yes, definitely",Less than half of the time,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,NaN,NaN,NaN,Learning about a codebase;Project planning;Wri...,NaN,"AI solutions that are almost right, but not quite",NaN,NaN,"Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
49149,49150,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (less than 10 hours per w...,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,10.0,"Developer, front-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,4.0,5.0,6.0,3.0,8.0,1.0,9.0,2.0,7.0,10.0,NaN,7.0,9.0,4.0,2.0,6.0,5.0,1.0,3.0,8.0,10.0,NaN,Software Development,6.0,12.0,4.0,9.0,7.0,11.0,3.0,14.0,13.0,5.0,2.0,1.0,8.0,15.0,10.0,NaN,Yes,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Very favorable,Neither trust nor distrust,Neither good or bad at handling complex tasks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0

In [13]:
ind_df.to_csv("mod.tsv",sep="\t")

In [14]:
ind_df.to_csv("mod.csv")

In [15]:
m=pd.read_csv("mod.tsv",sep="\t")

In [17]:
m.head()

,Unnamed: 0,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",NaN,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,NaN,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,NaN,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,NaN,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once every 2 - 3 months,Less than one year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
1,15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,NaN,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,NaN,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,NaN,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,NaN,NaN,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,NaN,NaN,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,NaN,NaN,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
2,46,47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,NaN,NaN,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,90,91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",NaN,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,NaN,NaN,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,NaN,NaN,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,NaN,NaN,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,NaN,NaN,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",Less than half of the time,NaN,Very favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Cybersecurity,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0
4,133,134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,NaN,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,NaN,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,NaN,NaN,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,NaN,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,NaN,AI agents have improved the quality of my code...,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,AutoGen (Microsoft),NaN,NaN,NaN,ChatGPT;Google Gemini;Microsoft Copilot,NaN,When I have ethical or security concerns about...,Problem solving,20109.0,9.0

In [18]:
ind_df.to_excel("mod.xlsx")

In [19]:
n=pd.read_excel("mod.xlsx")

In [20]:
n.head()

,Unnamed: 0,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",NaN,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,NaN,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,NaN,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,NaN,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once every 2 - 3 months,Less than one year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
1,15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,NaN,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,NaN,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,NaN,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,NaN,NaN,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,NaN,NaN,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,NaN,NaN,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
2,46,47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,NaN,NaN,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
3,90,91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",NaN,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,NaN,NaN,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,NaN,NaN,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,NaN,NaN,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,NaN,NaN,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",Less than half of the time,NaN,Very favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Cybersecurity,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0
4,133,134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,NaN,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,NaN,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,NaN,NaN,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,NaN,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,NaN,AI agents have improved the quality of my code...,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,AutoGen (Microsoft),NaN,NaN,NaN,ChatGPT;Google Gemini;Microsoft Copilot,NaN,When I have ethical or security concerns about...,Problem solving,20109.0,9.0

In [22]:
ind_df.to_json("mod.json")

In [24]:
p=pd.read_json("mod.json")

In [25]:
p

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
13,14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",None,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,None,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,None,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,None,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,None,None,None,None,None,None,Yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Yes,Less than once every 2 - 3 months,Less than one year,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,6.0
15,16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",None,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,None,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,None,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,None,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,None,None,None,None,None,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,None,None,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,None,None,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,None,None,None,None,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,None,None,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",None,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,None,None,None,AI agents have increased my productivity.;AI a...,None,None,None,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,None,Fireproof;LanceDB;Letta;Neo4j;Qdrant,None,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,None,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,None,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,None,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
46,47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,None,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,None,None,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,None,None,Yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,10.0
90,91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",None,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,None,None,Yes,None,None,None,None,None,None,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,None,None,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,None,None,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,None,None,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,None,None,None,None,None,None,None,None,None,None,None,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,None,None,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Yes, definitely",Less than half of the time,None,Very favorable,None,None,None,None,None,None,None,None,None,None,None,Software engineering;Cybersecurity,Language processing,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1.0,7.0
133,134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,None,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,None,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,None,None,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,None,None,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,None,None,None,None,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,None,None,None,None,None,None,None,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,None,None,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,None,None,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),None,None,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,None,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,None,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,None,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,None,None,AI agents have improved the quality of my code...,None,None,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,None,None,None,AutoGen (Microsoft),None,None,None,ChatGPT;Google Gemini;Microsoft Copilot,None,When I have ethical or security concerns about...,Problem solving,20109.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49132,49133,I code primarily as a hobby,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Not employed,None,NaN,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Videos (not associated ...,"No, I learned something that was not related t...",None,3.0,Student,None,None,None,None,Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Yes,I have neither consider or transitioned into a...,NaN,2.0,India,INR Indian rupee,NaN,Yes,HTML/CSS;Java;JavaScript;Python;Rust;TypeScript,Rust;TypeScript,Rust;TypeScript,None,None,Yes,MySQL;Redis;SQLite,None,None,None,None,Yes,Amazon Web Services (AWS);Ansible;Homebrew;Kub...,Kubernetes;npm,Kubernetes;npm,None,None,Yes,Node.js;React;Axum,Next.js;React;Axum,React;Axum,None,None,None,Cursor;Visual Studio Code,Cursor,Cursor,None,None,Tailwind CSS 4,Tailwind CSS 4,Tailwind CSS 4,None,None,MacOS,MacOS,None,None,None,None,None,Stack Overflow;YouTube,None,None,None,None,No,None,None,None,None,None,Yes,Less than once per month or monthly,Less than one year,Less than once every 2 - 3 months,Chat (people),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"No, not really",None,"Yes, I use AI tools daily",Favorable,Somewhat trust,Very well at handling complex tasks,None,Project planning;Generating content or synthet...,Learning about a codebase;Writing code;Documen...,Debugging or fixing code;Testing code;Committi...,Search for answers,I’ve become less confident in my own problem-s...,None,"No, but I plan to","Yes, to a great extent",None,None,None,None,None,None,None,Integrating AI agents with my existing tools a...,None,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,None,None,None,None,None,None,None,None,None,When I’m stuck and can’t explain the problem,Maths,NaN,NaN
49141,49142,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,1.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,5.0,Data engineer,20 to 99 employees,None,In-person,"Yes, I influenced the purchase of a substantia...",Work,4.0,6.0,1.0,3.0,5.0,2.0,8.0,9.0,7.0,10.0,None,7.0,6.0,2.0,1.0,8.0,9.0,5.0,3.0,4.0,10.0,None,Software Development,13.0,10.0,6.0,1.0,4.0,9.0,5.0,14.0,2.0,12.0,7.0,8.0,3.0,15.0,11.0,None,Yes,I have strongly considered changing my career ...,10.0,4.0,India,INR Indian rupee,750000.0,Yes,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Java;JavaScript;Python,Java;JavaScript;Python,PySpark,None,Yes,Databricks SQL;Dynamodb;MySQL;Snowflake;Amazon...,None,None,None,None,Yes,Amazon Web Services (AWS);Docker;Kubernetes;Te...,Amazon Web Services (AWS);Docker;Kubernetes;Te...,Amazon Web Services (AWS);Docker;Kubernetes;Te...,None,None,Yes,Express;Node.js,Express;Node.js;Spring Boot,Express;Node.js,None,None,Yes,Claude Code;Jupyter Notebook/JupyterLab;Visual...,Claude Code;Jupyter Notebook/JupyterLab;Visual...,Claude Code;Jupyter Notebook/JupyterLab;Visual...,None,None,None,None,None,None,None,Windows;Ubuntu,Windows;Ubuntu,GitHub;GitLab,GitHub;GitLab,GitHub;GitLab,None,None,Stack Overflow;YouTube;LinkedIn;Medium,Stack Overflow;YouTube;LinkedIn;Medium,Stack Overflow;YouTube;LinkedIn;Medium,None,None,Yes,Gemini (Pro Reasoning models);openAI GPT (chat...,Gemini (Pro Reasoning models);openAI GPT (chat...,Gemini (Pro Reasoning models);openAI GPT (chat...,None,None,Yes,Daily or almost daily,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,Job board,3.0,5.0,9.0,6.0,4.0,7.0,2.0,8.0,1.0,10.0,None,"Yes, definitely",Less than half of the time,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,None,None,None,Learning about a codebase;Project planning;Wri...,None,"AI solutions that are almost right, but not quite",None,None,"Yes, somewhat",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,8.0
49149,49150,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (less than 10 hours per w...,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",None,10.0,"Developer, front-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,4.0,5.0,6.0,3.0,8.0,1.0,9.0,2.0,7.0,10.0,None,7.0,9.0,4.0,2.0,6.0,5.0,1.0,3.0,8.0,10.0,None,Software Development,6.0,12.0,4.0,9.0,7.0,11.0,3.0,14.0,13.0,5.0,2.0,1.0,8.0,15.0,10.0,None,Yes,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,"Yes, I use AI tools daily",Very favorable,Neither trust nor distrust,Neither good or bad at handling complex tasks,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,5.0