In [26]:
import pandas as pd

In [27]:
orders = {
    "order_id": [1,2,3,4,5,6],
    "customer_id": [101,102,101,103,104,101],
    "product": ["Phone","Laptop","Phone","Tablet","Laptop","Tablet"],
    "quantity": [1,1,2,1,3,2]
}

customers = {
    "customer_id": [101,102,103,105],
    "name": ["Anway","Rahul","Lalo","Ghost"]
}

prices = {
    "product": ["Phone","Laptop","Tablet"],
    "price": [500,1200,300]
}

In [28]:
df1=pd.DataFrame(orders)
df2=pd.DataFrame(customers)
df3=pd.DataFrame(prices)

In [29]:
df1

   order_id  customer_id product  quantity
0         1          101   Phone         1
1         2          102  Laptop         1
2         3          101   Phone         2
3         4          103  Tablet         1
4         5          104  Laptop         3
5         6          101  Tablet         2

In [30]:
df2

   customer_id   name
0          101  Anway
1          102  Rahul
2          103   Lalo
3          105  Ghost

In [31]:
df3

  product  price
0   Phone    500
1  Laptop   1200
2  Tablet    300

In [38]:
df4=pd.merge(df1,df2,on="customer_id",how="left")
df4

   order_id  customer_id product  quantity   name
0         1          101   Phone         1  Anway
1         2          102  Laptop         1  Rahul
2         3          101   Phone         2  Anway
3         4          103  Tablet         1   Lalo
4         5          104  Laptop         3    NaN
5         6          101  Tablet         2  Anway

In [39]:
df5=pd.merge(df3,df4,on="product")
df5

  product  price  order_id  customer_id  quantity   name
0   Phone    500         1          101         1  Anway
1   Phone    500         3          101         2  Anway
2  Laptop   1200         2          102         1  Rahul
3  Laptop   1200         5          104         3    NaN
4  Tablet    300         4          103         1   Lalo
5  Tablet    300         6          101         2  Anway

In [41]:
df5["revenue"]=df5["price"]*df5["quantity"]
df5

  product  price  order_id  customer_id  quantity   name  revenue
0   Phone    500         1          101         1  Anway      500
1   Phone    500         3          101         2  Anway     1000
2  Laptop   1200         2          102         1  Rahul     1200
3  Laptop   1200         5          104         3    NaN     3600
4  Tablet    300         4          103         1   Lalo      300
5  Tablet    300         6          101         2  Anway      600

In [46]:
df5.pivot_table(index="customer_id",columns="product",values="revenue",aggfunc="sum")

product      Laptop   Phone  Tablet
customer_id
101             NaN  1500.0   600.0
102          1200.0     NaN     NaN
103             NaN     NaN   300.0
104          3600.0     NaN     NaN

In [48]:
users = {
    "user_id": [1, 2, 3, 4],
    "name": ["Anway", "Rahul", "Lalo", "Sofia"]
}

scores = {
    "user_id": [1, 2, 2, 3, 5],
    "score": [80, 90, 85, 70, 60]
}

In [49]:
df_1=pd.DataFrame(users)
df_2=pd.DataFrame(scores)

In [50]:
df_1

   user_id   name
0        1  Anway
1        2  Rahul
2        3   Lalo
3        4  Sofia

In [51]:
df_2

   user_id  score
0        1     80
1        2     90
2        2     85
3        3     70
4        5     60

In [56]:
pd.merge(df_1, df_2, on="user_id")
#pd.merge(df_1, df_2, on="user_id", how="left")
#pd.merge(df_1, df_2, on="user_id", how="right")
#pd.merge(df_1, df_2, on="user_id", how="outer")

   user_id   name  score
0        1  Anway     80
1        2  Rahul     90
2        2  Rahul     85
3        3   Lalo     70

In [57]:
sales = {
    "country": ["India","India","India","US","US","US"],
    "product": ["A","B","A","A","B","B"],
    "sales": [10,20,15,30,40,35]
}

In [59]:
df_sales=pd.DataFrame(sales)
df_sales

  country product  sales
0   India       A     10
1   India       B     20
2   India       A     15
3      US       A     30
4      US       B     40
5      US       B     35

In [62]:
df_sales.pivot_table(index="country",columns="product",values="sales")

product     A     B
country
India    12.5  20.0
US       30.0  37.5

In [63]:
employees = {
    "emp_id": [101,102,103,104],
    "name": ["Alice","Bob","Charlie","David"]
}

salary = {
    "emp_id": [101,102,105],
    "salary": [50000,60000,70000]
}

In [64]:
df_emp = pd.DataFrame(employees).set_index("emp_id")
df_sal = pd.DataFrame(salary).set_index("emp_id")

In [65]:
df_emp

           name
emp_id
101       Alice
102         Bob
103     Charlie
104       David

In [66]:
df_sal

        salary
emp_id
101      50000
102      60000
105      70000

In [67]:
df_emp.join(df_sal)

           name   salary
emp_id
101       Alice  50000.0
102         Bob  60000.0
103     Charlie      NaN
104       David      NaN

In [68]:
df_emp.join(df_sal,how="inner")

         name  salary
emp_id
101     Alice   50000
102       Bob   60000

In [69]:
df_emp.join(df_sal,how="outer")

           name   salary
emp_id
101       Alice  50000.0
102         Bob  60000.0
103     Charlie      NaN
104       David      NaN
105         NaN  70000.0

In [70]:
orders = {
    "city": ["Delhi","Delhi","Mumbai","Mumbai","Delhi","Mumbai"],
    "product": ["Phone","Laptop","Phone","Laptop","Phone","Phone"],
    "revenue": [500,1200,450,1300,550,480]
}

In [71]:
df=pd.DataFrame(orders)

In [72]:
df

     city product  revenue
0   Delhi   Phone      500
1   Delhi  Laptop     1200
2  Mumbai   Phone      450
3  Mumbai  Laptop     1300
4   Delhi   Phone      550
5  Mumbai   Phone      480

In [73]:
df.pivot_table(index="city",columns="product",values="revenue",aggfunc="sum")

product  Laptop  Phone
city
Delhi      1200   1050
Mumbai     1300    930