In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('height_weight.csv')
df

      gender     height      weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [4]:
df.describe()

             height        weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [6]:
mean_height=df['height'].mean()
std_height=df['height'].std()
mean_weight=df['weight'].mean()
std_weight=df['weight'].std()
df['z_score_height']=((df['height']-mean_height)/std_height)
df['z_score_weight']=((df['weight']-mean_weight)/std_weight)

In [23]:
q3_height=df['height'].quantile(0.25)
q5_height=df['height'].quantile(0.75)
q3_weight=df['weight'].quantile(0.25)
q5_weight=df['weight'].quantile(0.75)

In [24]:
iqr_height=q5_height-q3_height
iqr_weight=q5_weight-q3_weight

In [25]:
height_upper=q5_height+1.5*iqr_height
height_lower=q3_height-1.5*iqr_height
weight_upper=q5_weight+1.5*iqr_weight
weight_lower=q3_weight-1.5*iqr_weight

In [29]:
df1=df[(df['z_score_height']>-3) & (df['z_score_height']<3) & (df['z_score_weight']>-3) & (df['z_score_weight']<3)]
df1.head()

  gender     height      weight  z_score_height  z_score_weight
0   Male  73.847017  241.893563        1.943964        2.505672
1   Male  68.781904  162.310473        0.627505        0.027099
2   Male  74.110105  212.740856        2.012343        1.597726
3   Male  71.730978  220.042470        1.393991        1.825131
4   Male  69.881796  206.349801        0.913375        1.398680

In [31]:
df2=df[(df['height']>height_lower) & (df['height']<height_upper) & (df['weight']>weight_lower) & (df['weight']<weight_upper)]
df2.head()

  gender     height      weight  z_score_height  z_score_weight
0   Male  73.847017  241.893563        1.943964        2.505672
1   Male  68.781904  162.310473        0.627505        0.027099
2   Male  74.110105  212.740856        2.012343        1.597726
3   Male  71.730978  220.042470        1.393991        1.825131
4   Male  69.881796  206.349801        0.913375        1.398680